# Generated by Django 4.1.7 on 2023-04-25 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Uav',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=255)),
                ('model', models.CharField(blank=True, max_length=255, null=True)),
                ('weight', models.IntegerField()),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('airtime', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
