# Generated by Django 4.1.7 on 2023-04-25 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uav', '0002_customer_uav_availability_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='uav',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
